# Generated by Django 6.0.3 on 2026-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='discription',
            new_name='description',
        ),
    ]
